[build]
  command = "npm run build"
  publish = "dist"

# Local dev proxy (only used with `netlify dev`)
[[redirects]]
  from = "/api/*"
  to = "https://professorsite-t4utn376.b4a.run/api/:splat"
  status = 200
  force = true
